import type { Metadata } from "next";
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { Rubik } from 'next/font/google';
import { ReduxProvider } from '@/components/ReduxProvider';

config.autoAddCss = false;

const rubik = Rubik({
  weight: ['400'],
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "gamma-ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${rubik.className} ${rubik.variable}`}>
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
